name: 'AnthRepoSync'
author:
  - name: 'Anthony Kung'
    email: 'hi@anth.dev'
description: 'GitHub Action to sync repositories (push to another repo when push detected on current repo)'
inputs:
  RS_TARGET:
    description: 'Target repository in org/repo format e.g. Anthonykung/RepoSync'
    required: false
  RS_PAT:
    description: 'GitHub Personal Access Token (PAT) DO NOT PASS IT IN YOUR .yml, only secrets accepted'
    required: false
runs:
  using: "composite"
  steps:
    - name: Get current repo
      uses: actions/checkout@v2
      with:
        path: source
    - name: Get target repo
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.RS_TARGET }}
        token: ${{ secrets.RS_PAT }}
        path: target
    - run: ${{ github.action_path }}/RepoSync.sh
      shell: bash
branding:
  icon: 'refresh-cw'  
  color: 'orange'
