# @name RepoSync GitHub Action
# @file RepoSync.yml
# @author Anthony Kung (github.com/Anthonykung)
# @date October 25, 2021

name: RepoSync

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches:
    - ${{ secrets.RS_BRANCH }}  # For old repos, you might have `master` instead of `main`

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "sync"
  sync:
    name: Sync with GitHub repository
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get current repo
        uses: actions/checkout@v2
        with:
          path: source
          
      - name: Get target repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.RS_TARGET }}  # Create a secret with your GitHub repo in org/repo format e.g. Anthonykung/RepoSync
          token: ${{ secrets.RS_PAT }}  # Create a PAT with public repo access and put it as a secret named PUBLIC_GITHUB_REPO
          path: target                              # (GitHub -> Repo -> Settings -> Secrets -> New repository secret)
          
      # You can add more targets if you want

      # Runs a set of commands using the runners shell
      - name: Copy source to target and push
        run: |
          rsync -r --exclude '.git' $GITHUB_WORKSPACE/source/* $GITHUB_WORKSPACE/target
          cd $GITHUB_WORKSPACE/target
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -am "Generated update from RepoSync GitHub Action"
          git push
          
      # If that failed use the following
      # git remote add upstream https://github.com/Anthonykung/RepoSync.git in org/repo format
